
name: Build Flutter Windows

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    defaults:
      run:
        working-directory: bikecontrol_test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Enable Windows desktop
        run: flutter config --enable-windows-desktop

      - name: Install dependencies
        run: flutter pub get

      - name: Build Windows Release
        run: flutter build windows --release

      - name: Upload Windows executable
        uses: actions/upload-artifact@v4
        with:
          name: BIKE-Windows
          path: bikecontrol_test/build/windows/x64/runner/Release/
          if-no-files-found: error
