name: Build Windows EXE

on:
  push:
    branches: [ main, master ]
  workflow_dispatch: 

jobs:
  build:
    runs-on: windows-latest

    defaults:
      run:
        working-directory: Bikecontrol_test

    steps:
    - name: Clona il codice
      uses: actions/checkout@v4

    - name: Configura Java
      uses: actions/setup-java@v5
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Installa ambiente C++ (Forzato x64)
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: amd64

    - name: Configura Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    - name: Pulisci e forza downgrade delle dipendenze
      run: |
        flutter clean
        # Forza il downgrade del pacchetto prop alla versione che supporta 'keyPrefix'
        flutter pub downgrade prop 
        flutter pub get

    - name: Genera file di localizzazione
