name: Build Windows EXE

on:
  push:
    branches: [ main, master ]
  workflow_dispatch: 

jobs:
  build:
    runs-on: windows-latest

    defaults:
      run:
        working-directory: Bikecontrol_test # 1. Sostituito qui per la cartella di lavoro

    steps:
    - name: Clona il codice
      uses: actions/checkout@v4

    - name: Configura Java
      uses: actions/setup-java@v5
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Installa ambiente C++ (Forzato x64)
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: amd64

    - name: Configura Flutter
      uses: subosito/flutter-action@v2
      env:
        FORCE_JUST_JAVASCRIPT_ACTIONS_TO_NODE24: true
      with:
        channel: 'stable'

    - name: Pulisci e installa dipendenze
      run: |
        flutter clean
        flutter pub get

    - name: Genera file di localizzazione
      run: flutter pub run intl_utils:generate

    - name: Abilita il supporto Windows
      run: flutter config --enable-windows-desktop

    - name: Compila il file EXE
      run: flutter build windows --release

    - name: Salva i file compilati (Artifact)
      uses: actions/upload-artifact@v4
      with:
        name: applicazione-windows
        path: Bikecontrol_test/build/windows/runner/Release/ # 2. Sostituito qui per il salvataggio dell'EXE
